ko_fi: nikmedoed

buy_me_a_coffee: nikmedoed

custom:
  - https://boosty.to/nikmedoed/donate
  - https://paypal.me/etonikmedoed
  - https://yoomoney.ru/to/4100119049495394
  - https://github.com/nikmedoed#-support-my-work
